salesforce-sapi:
  client_id: "![mii1WV3g93XO6rZyL7QbmMWT1wc7n0AhFGe69mQST7cqpRLAIoGYvg==]"
  client_secret: "![HxmvpbL6t6ybO4rjt9Hl4c4VdUbVJaTVPVvdbytASxT5nCQUMy6/gg==]"

dealernet-sapi:
  client_id: "![mii1WV3g93XO6rZyL7QbmMWT1wc7n0AhFGe69mQST7cqpRLAIoGYvg==]"
  client_secret: "![HxmvpbL6t6ybO4rjt9Hl4c4VdUbVJaTVPVvdbytASxT5nCQUMy6/gg==]"
  
fandi-sapi:
  client_id: "![GqReF7IZh1+sdwVLhwUONvxUsjzgyox9np284XCOMAlhlNN/blhB2g==]"
  client_secret: "![haFQcMohR+vuzL7Ei8WXRXt1g1Q7hJPEdn2DY8alyFF87gudOHfFcA==]"